# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'schedule' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for schedule
  pod 'Toast-Swift', '~> 5.0.0'

  target 'scheduleTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'scheduleUITests' do
    # Pods for testing
  end

end
